-- M041 rollback: remove authenticated grants from child RPCs
REVOKE EXECUTE ON FUNCTION public.revoke_child_session(p_session_token text)            FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.search_children(p_query text, p_exclude_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_circle(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_circle_history(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_outgoing_pending_requests(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_pending_requests(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.send_circle_request(p_from_id uuid, p_to_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.accept_circle_request(p_request_id uuid, p_acting_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_circle_request(p_from_id uuid, p_to_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.decline_circle_request(p_request_id uuid, p_acting_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.remove_from_circle(p_child_id uuid, p_friend_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_active_requests(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_resolved_sent_requests(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.create_money_request(p_from_id uuid, p_amount numeric, p_deadline_days integer, p_session_token text, p_device_id text, p_reason text, p_reason_emoji text, p_viewer_ids uuid[]) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_money_request(p_request_id uuid, p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fund_money_request(p_request_id uuid, p_funder_id uuid, p_amount numeric, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.repay_money_request(p_request_id uuid, p_borrower_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_child_stats(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_child_transactions(p_child_id uuid, p_session_token text, p_device_id text, p_limit integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_activity_feed(p_child_id uuid, p_session_token text, p_device_id text, p_limit integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_loan_history(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.enable_biometric(p_child_id uuid, p_device_id text, p_biometric_token_hash text, p_session_token text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.disable_biometric(p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.register_child_device_token(p_child_id uuid, p_session_token text, p_device_id text, p_expo_push_token text, p_platform text, p_app_version text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.deregister_child_device_token(p_expo_push_token text, p_child_id uuid, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_profile_image(p_child_id uuid, p_image_url text, p_session_token text, p_device_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.record_weekly_streak(p_child_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.record_weekly_streak(p_child_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_streak_expiry(p_child_id uuid)  FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.check_streak_expiry(p_child_id uuid)  FROM anon;
