export type RootStackParamList = {
  Carousel: undefined;
  Email: undefined;
  Password: undefined;
  Mobile: undefined;
  Notifications: undefined;
  DisplayName: undefined;
  Identity: undefined;
  Address: undefined;
  HomeAddress: undefined;
  Verifying: undefined;
  ChildDetails: undefined;
  SafetyPool: undefined;
  SelectAccount: undefined;
  WhoIsLoggingIn: { newAccount?: boolean } | undefined;
  GetApp: undefined;
  ParentEmailLogin: undefined;
  ChildLogin: undefined;
  ParentPasscode: { mode: 'create' | 'confirm' | 'enter'; pinToConfirm?: string };
  ChildTabs: undefined;
  ParentTabs: undefined;
  TrustStats: undefined;
  RequestMoney: undefined;
  AvatarPicker: undefined;
  Leaderboard: undefined;
  ActivityFeed: undefined;
  AddFriends: undefined;
  ChildSettings: undefined;
  PaymentMethods: undefined;
  ParentAccountDetails: undefined;
  ParentNotifications: undefined;
  RateTruzo: undefined;
  BiometricSetup: undefined;
  BiometricLogin: undefined;
  ChildProfile: undefined;
};
